# Architecture
arch: cResNet18 

# ===== Dataset ===== #
data: /mnt/disk1/datasets
set: CIFAR10
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cifar_piecewise

# ===== Network training config ===== #
epochs: 160
weight_decay: 0.0005
momentum: 0.9
batch_size: 256

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: -1 # Override
init: kaiming_uniform
mode: fan_in
nonlinearity: relu

# ===== Hardware setup ===== #
workers: 4