# Architecture
arch: VGG16 

# ===== Dataset ===== #
data: /mnt/disk1/datasets
set: CIFAR10
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cifar_piecewise

# ===== Network training config ===== #
epochs: 160
weight_decay: 0.0005
momentum: 0.9
batch_size: 256

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
init: signed_constant
freeze_weights: True
mode: fan_in
nonlinearity: relu
prune_rate: -1

# ===== Hardware setup ===== #
workers: 4